spring:
  application:
    name: my-consumer-feign
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:21888/eureka/
#开启熔断器
feign:
  hystrix:
    enabled: true
